/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RT_LGCNN;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wolez
 */
public class GUI_RT_LGCNN extends javax.swing.JFrame {

    ThreadMouse Mouse = new ThreadMouse();
    ThreadFitur fitur = new ThreadFitur();
    Thread ThreadM = new Thread(Mouse);
    Thread ThreadF = new Thread(fitur);

    /**
     * Creates new form Coba
     */
    public GUI_RT_LGCNN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HasilHuruf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.desktop);
        setLocation(new java.awt.Point(500, 300));

        HasilHuruf.setBackground(new java.awt.Color(255, 255, 153));
        HasilHuruf.setFont(new java.awt.Font("Times New Roman", 1, 150)); // NOI18N
        HasilHuruf.setForeground(new java.awt.Color(0, 153, 51));
        HasilHuruf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HasilHuruf.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StartHereButton.jpg"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HasilHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(HasilHuruf, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
                try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI_RT_LGCNN.class.getName()).log(Level.SEVERE, null, ex);
        }
//        LABEL.setText("Mouse di enter");
//        Mouse.setJalanMouse(false);
//        System.out.println("keaddaan "+ThreadM.isInterrupted() + " "+ThreadM.isAlive());
        ThreadF.start();
        //new Thread(Mouse).interrupt();
        this.dispose();
//        new Thread(Mouse).stop();
    }//GEN-LAST:event_jLabel2MouseEntered

    public void RunMouse() {
        ThreadM.start();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_RT_LGCNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_RT_LGCNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_RT_LGCNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_RT_LGCNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        GUI_RT_LGCNN Gui = new GUI_RT_LGCNN();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_RT_LGCNN().setVisible(true);
            Gui.RunMouse();
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel HasilHuruf;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
