/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LgcnnManual;

import com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Wolez
 */
public class GUI_Manual extends javax.swing.JFrame {

    DecimalFormat df = new DecimalFormat("#.##");

    public static String DirTraining;
    public static String DirTesting;

    public static double TimeTrainLgcnn;
    public static double TimeTestLgcnn;

    /**
     * Creates new form NewJFrame
     */
    public GUI_Manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtTesting = new javax.swing.JButton();
        TextTraining = new javax.swing.JTextField();
        TextTesting = new javax.swing.JTextField();
        BtTraining = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BenarLgcnn = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        SalahLgcnn = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        AkurasiLgcnn = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        WaktuTrainLgcnn = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        WaktuTestLgcnn = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        IterasiLgcnn = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Btlgcnn = new javax.swing.JButton();
        VarianLgcnn = new javax.swing.JTextField();
        EpochLgcnn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manual Testing (RB-LGCNN, LGCNN and KNN)");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SIBI Sign Language Recognition With Leap Motion Controller");

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Data Testing ");

        jLabel1.setText("Data Training");

        BtTesting.setText("Open File");
        BtTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTestingActionPerformed(evt);
            }
        });

        TextTraining.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTrainingActionPerformed(evt);
            }
        });

        TextTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTestingActionPerformed(evt);
            }
        });

        BtTraining.setText("Open File");
        BtTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTrainingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextTraining)
                    .addComponent(TextTesting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtTraining, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtTesting, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtTraining)
                    .addComponent(TextTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextTesting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtTesting)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Result :");

        jLabel28.setText("Benar");

        jLabel29.setText("Salah");

        jLabel30.setText("Akurasi");

        jLabel31.setText("W. Train");

        jLabel36.setText("W. Test");

        jLabel39.setText("Iterasi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BenarLgcnn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(SalahLgcnn)
                            .addComponent(AkurasiLgcnn))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IterasiLgcnn)
                                    .addComponent(WaktuTrainLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(WaktuTestLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BenarLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(IterasiLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalahLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(WaktuTrainLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AkurasiLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel36)
                    .addComponent(WaktuTestLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("LGCNN :");

        Btlgcnn.setText("Proses");
        Btlgcnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtlgcnnActionPerformed(evt);
            }
        });

        VarianLgcnn.setText("0");
        VarianLgcnn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VarianLgcnnMouseClicked(evt);
            }
        });

        EpochLgcnn.setText("0");
        EpochLgcnn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EpochLgcnnMouseClicked(evt);
            }
        });

        jLabel16.setText("Varian");

        jLabel17.setText("Epoch");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(VarianLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(EpochLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(Btlgcnn)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EpochLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(Btlgcnn))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VarianLgcnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTrainingActionPerformed
        // TODO add your handling code here:
        TextTraining.setText("No Selection ");
    }//GEN-LAST:event_TextTrainingActionPerformed

    private void BtTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTrainingActionPerformed
        // TODO add your handling code here:
        JFileChooser DirTrain = new JFileChooser();
        DirTrain.setCurrentDirectory(new java.io.File("."));
        DirTrain.setDialogTitle("choosertitle");
        DirTrain.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        DirTrain.setAcceptAllFileFilterUsed(false);
//        String A = chooser.getSelectedFile();

        if (DirTrain.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            TextTraining.setText("" + DirTrain.getSelectedFile());
            DirTraining = "" + DirTrain.getSelectedFile();
//            System.out.println(DirTraining);
//            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
//            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        } else {
            TextTraining.setText("No Selection ");
        }
    }//GEN-LAST:event_BtTrainingActionPerformed

    private void TextTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTestingActionPerformed
        // TODO add your handling code here:
        TextTesting.setText("No Selection ");
    }//GEN-LAST:event_TextTestingActionPerformed

    private void BtTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTestingActionPerformed
        // TODO add your handling code here:
        JFileChooser DirTest = new JFileChooser();
        DirTest.setCurrentDirectory(new java.io.File("."));
        DirTest.setDialogTitle("choosertitle");
        DirTest.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        DirTest.setAcceptAllFileFilterUsed(false);
//        String A = chooser.getSelectedFile();

        if (DirTest.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            TextTesting.setText("" + DirTest.getSelectedFile());
            DirTesting = "" + DirTest.getSelectedFile();
//            System.out.println(DirTraining);
//            System.out.println("getCurrentDirectory(): " + chooser.getCurrentDirectory());
//            System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
        } else {
            TextTesting.setText("No Selection ");
        }
    }//GEN-LAST:event_BtTestingActionPerformed

    private void BtlgcnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtlgcnnActionPerformed
        try {
            // TODO add your handling code here:
            LgcnnTrain.GVarians = Double.parseDouble(VarianLgcnn.getText());
            LgcnnTrain.Epochs = Integer.parseInt(EpochLgcnn.getText());

            MainLGCNN();

            BenarLgcnn.setText(String.valueOf(LgcnnTest.Benar));
            SalahLgcnn.setText(String.valueOf(LgcnnTest.Salah));
            AkurasiLgcnn.setText(String.valueOf(df.format(LgcnnTest.Akurasi)) + " %");
            IterasiLgcnn.setText(String.valueOf(LgcnnTrain.Iterasi));
            WaktuTrainLgcnn.setText(String.valueOf(df.format(TimeTrainLgcnn / 1000)) + " s");
            WaktuTestLgcnn.setText(String.valueOf(df.format(TimeTestLgcnn / 1000)) + " s");
        } catch (IOException ex) {
            Logger.getLogger(GUI_Manual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtlgcnnActionPerformed

    private void VarianLgcnnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VarianLgcnnMouseClicked
        // TODO add your handling code here:
        VarianLgcnn.setText("");
    }//GEN-LAST:event_VarianLgcnnMouseClicked

    private void EpochLgcnnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EpochLgcnnMouseClicked
        // TODO add your handling code here:
        EpochLgcnn.setText("");
    }//GEN-LAST:event_EpochLgcnnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void CLC() throws IOException, InterruptedException {
        new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
    }

    public static void MainLGCNN() throws IOException {
        // TODO code application logic here
        System.out.println("Program LGCNN dengan Tipe data Atribut Numerik");

        long cTimeTrainLgcnn1;
        long cTimeTrainLgcnn2;

        BacaFile fileTrain = new BacaFile();
        fileTrain.bacaFileToArray(DirTraining); //"file/data_training.csv"
        fileTrain.defenisiClass();
        fileTrain.ambilDataLengkap();
        fileTrain.ambilAtributTarget();
        Tools a = new Tools();
        //a.printArray(fileTrain.dataLkp);
        double[][][] Fold = new double[10][27][13];
        for (int i = 1; i <= 10; i++) {
            double[][] tmp = new double[27][13];
            for (int j = 1; j <= 27; j++) {
                int index = (j - 1) * 10 + i;
                tmp[j - 1] = fileTrain.dataLkp[index - 1];
            }
            Fold[i - 1] = tmp;
        }

        //----------------------iterasi pelatihan----------------------
        ArrayList<Integer> Iterasi = new ArrayList();
        Iterasi.add(1);
        Iterasi.add(2);
        Iterasi.add(3);
        Iterasi.add(4);
        Iterasi.add(5);
        Iterasi.add(6);
        Iterasi.add(7);
        Iterasi.add(8);
        Iterasi.add(9);
        Iterasi.add(10);

        LgcnnTrain lgcnnTrain = new LgcnnTrain();
        LgcnnTest lgcnnTest = new LgcnnTest();
        for (int i = 0; i < Fold.length; i++) {
            System.out.println("ITERASI " + i);
            ArrayList<Integer> cpIterasi = (ArrayList<Integer>) Iterasi.clone();
            double[][] testData = Fold[cpIterasi.get(i) - 1];
            cpIterasi.remove(i);
            double[][][] trainData = new double[cpIterasi.size()][27][13];
            System.out.println(cpIterasi.size());
            for (int j = 0; j < cpIterasi.size(); j++) {
                trainData[j] = Fold[cpIterasi.get(j) - 1];
            }
//            a.printArray(testData,"Data Uji");
//            a.printArray(trainData,"Data Latih");

            for (int k = 0; k < trainData.length; k++) {
                lgcnnTrain.ProsesLatihLGCNN(trainData[k]);
            }
            lgcnnTest.ProsesTestLGCNN(testData);
        }

//        LgcnnTrain lgcnnTrain = new LgcnnTrain();
//        cTimeTrainLgcnn1 = System.currentTimeMillis();
//        lgcnnTrain.ProsesLatihLGCNN(fileTrain.dataTraining);
//        cTimeTrainLgcnn2 = System.currentTimeMillis();
//        TimeTrainLgcnn = cTimeTrainLgcnn2 - cTimeTrainLgcnn1;
//
//        long cTimeTestLgcnn1;
//        long cTimeTestLgcnn2;
//
//        BacaFileTest fileTest = new BacaFileTest();
//        fileTest.bacaFileToArray(DirTesting);
//        fileTest.defenisiClassTest();
//        fileTest.ambilAtributTargetTest();
//        fileTest.ambilDataTesting();
//        LgcnnTest lgcnnTest = new LgcnnTest();
//        cTimeTestLgcnn1 = System.currentTimeMillis();
//        lgcnnTest.ProsesTestLGCNN(fileTest.dataTesting);
//        cTimeTestLgcnn2 = System.currentTimeMillis();
//        TimeTestLgcnn = cTimeTestLgcnn2 - cTimeTestLgcnn1;
    }

    public static void TxtTrain() {
        TextTraining.setText("No Selection");
        TextTesting.setText("No Selection");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Manual().setVisible(true);
                TxtTrain();
//                try {
//                    Utama();
//                } catch (IOException ex) {
//                    Logger.getLogger(GUI_Manual.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField AkurasiLgcnn;
    public javax.swing.JTextField BenarLgcnn;
    private javax.swing.JButton BtTesting;
    private javax.swing.JButton BtTraining;
    private javax.swing.JButton Btlgcnn;
    public static javax.swing.JTextField EpochLgcnn;
    public static javax.swing.JTextField IterasiLgcnn;
    private javax.swing.JTextField SalahLgcnn;
    public static javax.swing.JTextField TextTesting;
    public static javax.swing.JTextField TextTraining;
    public static javax.swing.JTextField VarianLgcnn;
    private javax.swing.JTextField WaktuTestLgcnn;
    private javax.swing.JTextField WaktuTrainLgcnn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
